2025-10-14 15:31:01,768 - INFO - [StreamingAnalytics] - ‚úÖ Spark Session initialis√©e
2025-10-14 15:31:32,280 - WARNING - [StreamingAnalytics] - ‚ö†Ô∏è MongoDB non disponible: localhost:27017: [WinError 10061] Aucune connexion n‚Äôa pu √™tre √©tablie car l‚Äôordinateur cible l‚Äôa express√©ment refus√©e (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68ee509553597f20d4c5892f, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] Aucune connexion n‚Äôa pu √™tre √©tablie car l‚Äôordinateur cible l‚Äôa express√©ment refus√©e (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>, stockage en m√©moire uniquement
2025-10-14 15:31:32,288 - INFO - [StreamingAnalytics] - üöÄ D√©marrage Spark Streaming...
2025-10-14 15:31:33,398 - ERROR - [StreamingAnalytics] - ‚ùå Erreur Spark Streaming: Failed to find data source: kafka. Please deploy the application as per the deployment section of Structured Streaming + Kafka Integration Guide.
2025-10-14 15:31:33,706 - INFO - [StreamingAnalytics] - ‚úÖ Streaming arr√™t√©
2025-10-14 15:31:34,206 - INFO - [py4j.clientserver] - Error while receiving.
Traceback (most recent call last):
  File "C:\Users\aitnd\AppData\Local\Programs\Python\Python312\Lib\site-packages\py4j\clientserver.py", line 535, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aitnd\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Une connexion existante a d√ª √™tre ferm√©e par l‚Äôh√¥te distant
2025-10-14 15:31:34,229 - INFO - [py4j.clientserver] - Closing down clientserver connection
2025-10-14 15:31:34,229 - ERROR - [root] - Exception while sending command.
Traceback (most recent call last):
  File "C:\Users\aitnd\AppData\Local\Programs\Python\Python312\Lib\site-packages\py4j\clientserver.py", line 535, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aitnd\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Une connexion existante a d√ª √™tre ferm√©e par l‚Äôh√¥te distant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aitnd\AppData\Local\Programs\Python\Python312\Lib\site-packages\py4j\java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aitnd\AppData\Local\Programs\Python\Python312\Lib\site-packages\py4j\clientserver.py", line 566, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
2025-10-14 15:31:34,230 - INFO - [py4j.clientserver] - Closing down clientserver connection
2025-10-14 15:31:54,418 - INFO - [StreamingAnalytics] - ‚úÖ Spark Session initialis√©e
2025-10-14 15:32:24,526 - WARNING - [StreamingAnalytics] - ‚ö†Ô∏è MongoDB non disponible: localhost:27017: [WinError 10061] Aucune connexion n‚Äôa pu √™tre √©tablie car l‚Äôordinateur cible l‚Äôa express√©ment refus√©e (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68ee50caaf190f6eca4a1d53, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] Aucune connexion n‚Äôa pu √™tre √©tablie car l‚Äôordinateur cible l‚Äôa express√©ment refus√©e (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>, stockage en m√©moire uniquement
2025-10-14 15:32:24,532 - INFO - [StreamingAnalytics] - üöÄ D√©marrage Spark Streaming...
2025-10-14 15:32:25,315 - ERROR - [StreamingAnalytics] - ‚ùå Erreur Spark Streaming: Failed to find data source: kafka. Please deploy the application as per the deployment section of Structured Streaming + Kafka Integration Guide.
2025-10-14 15:32:25,559 - INFO - [StreamingAnalytics] - ‚úÖ Streaming arr√™t√©
2025-10-14 15:32:25,579 - INFO - [py4j.clientserver] - Closing down clientserver connection
2025-10-14 15:34:33,165 - INFO - [StreamingAnalytics] - ‚úÖ Spark Session initialis√©e
2025-10-14 15:35:03,210 - WARNING - [StreamingAnalytics] - ‚ö†Ô∏è MongoDB non disponible: localhost:27017: [WinError 10061] Aucune connexion n‚Äôa pu √™tre √©tablie car l‚Äôordinateur cible l‚Äôa express√©ment refus√©e (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68ee51693f573ce51cdf91e0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] Aucune connexion n‚Äôa pu √™tre √©tablie car l‚Äôordinateur cible l‚Äôa express√©ment refus√©e (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>, stockage en m√©moire uniquement
2025-10-14 15:35:03,223 - INFO - [StreamingAnalytics] - üöÄ D√©marrage Spark Streaming...
2025-10-14 15:35:04,564 - ERROR - [StreamingAnalytics] - ‚ùå Erreur Spark Streaming: Failed to find data source: kafka. Please deploy the application as per the deployment section of Structured Streaming + Kafka Integration Guide.
2025-10-14 15:35:05,011 - INFO - [StreamingAnalytics] - ‚úÖ Streaming arr√™t√©
2025-10-14 15:35:05,054 - INFO - [py4j.clientserver] - Closing down clientserver connection
